import re
import os

with open("videodownloader/gui/app.py", "r", encoding="utf-8") as f:
    content = f.read()

translations = {
    "VideoDownloader — 通用视频下载器": "VideoDownloader - Universal Video Downloader",
    "视频/课程 URL:": "Video/Course URL:",
    "下载平台:": "Platform:",
    "通用 (YouTube/Bilibili 等)": "Generic (YouTube/Bilibili etc.)",
    "最高画质:": "Max Quality:",
    "输出目录:": "Output Dir:",
    "浏览...": "Browse...",
    "Cookies 来源:": "Cookies:",
    "无 (免登录)": "None (No login)",
    "Chrome 浏览器": "Chrome Browser",
    "Edge 浏览器": "Edge Browser",
    "Firefox 浏览器": "Firefox Browser",
    "Brave 浏览器": "Brave Browser",
    "剪贴板 (粘贴文本)": "Clipboard (Paste text)",
    "选择 cookies.txt 文件...": "Select cookies.txt...",
    "日志级别:": "Log Level:",
    "并发线程:": "Concurrency (Threads):",
    "等待下载...": "Waiting...",
    "开始下载": "Start Download",
    "⏸ 暂停": "⏸ Pause",
    "▶继续": "▶ Resume",
    "⏹ 停止": "⏹ Stop",
    "下载附加选项": "Additional Options",
    "下载字幕 (.vtt/.srt)": "Download Subtitles (.vtt/.srt)",
    "选集范围 (例: 1-5, 8):": "Playlist Items (e.g. 1-5, 8):",
    "留空则默认下载全部": "Leave blank to download all",
    "DeepLearning.AI 附加选项": "DeepLearning.AI Options",
    "指定周卡 (例: 1 2 4):": "Specific Weeks (e.g. 1 2 4):",
    "错误": "Error",
    "此操作不支持该系统。": "Operation not supported.",
    "确  认": "Confirm",
    "取消": "Cancel",
    "确认": "Confirmation",
    "确定要停止当前下载(会取消后续任务)吗？": "Stop current download and cancel queued tasks?",
    "正在强制停止，请稍候...": "Force stopping, please wait...",
    "已暂停: ": "Paused: ",
    "正在下载: ": "Downloading: ",
    "   |   速度: ": "   |   Speed: ",
    "并发下载中 (多线程活动)... 请查看左侧日志": "Concurrent downloading... Check logs",
    "已下载完成: ": "Finished: ",
    "，正在合并或处理...": ", processing/merging...",
    "警告": "Warning",
    "请输入 URL 或 Course Slug": "Please enter URL or Course Slug",
    "正在下载...": "Downloading...",
    "准备下载...": "Preparing...",
    "启动期间如有卡顿属于正常现象。": "Slight stuttering during startup is normal.",
    "欢迎使用 VideoDownloader GUI 版本！由于部分环境缺少配置，": "Welcome to VideoDownloader GUI! ",
    "未找到需要下载的课时内容": "No downloadable content found",
    "没有解析出任何下载任务。": "No download tasks could be parsed.",
    "发现 ": "Found ",
    " 个下载子任务，准备下载...": " sub-tasks, preparing download...",
    "🚫 队列执行已中止": "🚫 Queue execution aborted",
    "解析真实文件名中...": "Resolving actual filename...",
    "\n---> 开始执行任务 [": "\n---> Starting task [",
    "]: ": "]: ",
    "即将开始: ": "Starting soon: ",
    " (包含失败项)": " (Includes failed items)",
    "🚫 任务已终止: ": "🚫 Task terminated: ",
    "执行期间异常: ": " exception during execution: ",
    " (异常)": " (Exception)",
    "⚠️ 部分/瑕疵: ": "⚠️ Partial: ",
    "🚫 子任务已终止: ": "🚫 Sub-task terminated: ",
    "🛑 下载已被用户提前手动停止。完成情况: ": "🛑 Download manually stopped. Completions: ",
    " 成功。": " successful.",
    "✅ 队列执行完毕！成功 ": "✅ Queue execution finished! Success: ",
    "，部分/瑕疵 ": ", Partial: ",
    "，完全失败 ": ", completely failed: ",
    "⚠️ 以下任务未能完整下载，请检查其页面状态：": "⚠️ The following tasks failed to download completely:",
    "有任务未能成功下载": "Some tasks failed to download",
    "在刚才的批量队列中，有 ": "In the previous batch queue, ",
    " 个任务无法完整下载：\n\n": " tasks failed to finish:\n\n",
    "\n\n详情请查看左侧日志区域。": "\n\nCheck logs for details.",
    "❌ 下载过程发生未知错误: ": "❌ Unknown error occurred: ",
    "下载已终止 (点击重来)": "Terminated (Click to restart)",
    "已手动打断。已完成 ": "Manually interrupted. Completed ",
    " 个任务。": " tasks.",
    "下载崩溃 (点击重试)": "Crashed (Click to retry)",
    "执行异常，请查看日志。(点击重试)": "Execution exception, check logs (Click to retry)",
    "✅ 全部完成 (点击开始新下载)": "✅ All Completed (Click to restart)",
    "所有任务均已处理完毕！": "All tasks have been processed!",
    "Text Files": "Text Files",
    "All Files": "All Files"
}

for k, v in translations.items():
    content = content.replace(f'"{k}"', f'"{v}"')
    content = content.replace(f"'{k}'", f"'{v}'")

with open("videodownloader/gui/app.py", "w", encoding="utf-8") as f:
    f.write(content)

print("Translation strings replaced.")
